### ISSUE TITLE
Alda sandbox setup

### ISSUE THREAD

**Issue by KaseyW31** [GreenBankObservatory/summer_onboarding_2023#6]
Follow setup instructions on https://github.com/GreenBankObservatory/alda

**Comment by tchamberlin** [comment]
We'll need to work together on this -- looks like we can get started tomorrow!

**Comment by KaseyW31** [comment]
- Created an environment and followed instructions (excluding enabling PostgreSQL)
- Installed a numpy version separately, then installed pyslalib
- Installed dependencies using pdm
- Copied and made changes to alda/.env
- Ran server and logged in as a test user
